Repository My-Epitech-Organisation/Survivor, pull requests merged in 2025-09, with the labels that each got.

#5 Add new templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/chore.md
  .github/ISSUE_TEMPLATE/spike.md
  .github/ISSUE_TEMPLATE/task.md
Labels: documentation

#8 remove related milestone section from task template
  .github/ISSUE_TEMPLATE/task.md
Labels: enhancement

#28 fix (compiling): public dir is now back
  frontend/public/.gitkeep
Labels: bug

#43 Create the login and signin panels
  frontend/app/about/page.tsx
  frontend/app/events/page.tsx
  frontend/app/globals.css
  frontend/app/login/page.tsx
  frontend/app/news/page.tsx
  frontend/app/page.tsx
  frontend/app/projects/page.tsx
  frontend/app/search/page.tsx
  frontend/app/signup/page.tsx
  frontend/components.json
  frontend/components/Footer.tsx
  frontend/components/Navigation.tsx
  frontend/components/SignUp.tsx
  frontend/components/login-form.tsx
  frontend/components/ui/button.tsx
  frontend/components/ui/card.tsx
  frontend/components/ui/input.tsx
  frontend/components/ui/label.tsx
  frontend/lib/utils.ts
  frontend/package.json
Labels: enhancement

#47 News and NewsDetails fetch upon migration
  backend/admin_panel/__init__.py
  backend/admin_panel/admin.py
  backend/admin_panel/apps.py
  backend/admin_panel/migrations/0001_initial.py
  backend/admin_panel/migrations/0002_newsdetail_image.py
  backend/admin_panel/migrations/__init__.py
  backend/admin_panel/models.py
  backend/admin_panel/serializers.py
  backend/admin_panel/tests.py
  backend/admin_panel/urls.py
  backend/admin_panel/views.py
  backend/backend/settings.py
  backend/backend/urls.py
  backend/init/signals.py
  backend/init/utils.py
  backend/models.py
  backend/poc/admin.py
  backend/poc/migrations/0001_initial.py
  backend/poc/models.py
  backend/poc/serializers.py
  backend/poc/socketio_server.py
  backend/poc/views.py
  backend/requirement.txt
Labels: enhancement

#54 52 task frontend reponsivity on project section
  frontend/app/projects/page.tsx
  frontend/components/Navigation.tsx
Labels: enhancement

#63 Skeleton of the startup area finished, this area is available after login
  frontend/app/layout.tsx
  frontend/app/page.tsx
  frontend/app/projects/page.tsx
  frontend/app/startup/dashboard/page.tsx
  frontend/app/startup/layout.tsx
  frontend/app/startup/messaging/page.tsx
  frontend/app/startup/opportunities/page.tsx
  frontend/app/startup/profile/page.tsx
  frontend/components/Navigation.tsx
  frontend/components/StartupNavigation.tsx
  frontend/components/login-form.tsx
  frontend/contexts/AuthContext.tsx
Labels: enhancement

#75 BACKEND | Fetch and update database with JEB api
  backend/admin_panel/admin.py
  backend/admin_panel/migrations/0003_event.py
  backend/admin_panel/migrations/0004_founder_startuplist_startupdetail.py
  backend/admin_panel/migrations/0005_alter_startupdetail_founders.py
  backend/admin_panel/migrations/0006_alter_founder_name.py
  backend/admin_panel/migrations/0007_user.py
  backend/admin_panel/migrations/0008_investor.py
  backend/admin_panel/migrations/0009_partner.py
  backend/admin_panel/migrations/0010_alter_startupdetail_founders.py
  backend/admin_panel/models.py
  backend/admin_panel/serializers.py
  backend/admin_panel/urls.py
  backend/admin_panel/views.py
  backend/backend/settings.py
  backend/init/signals.py
  backend/init/utils.py
  backend/models.py
Labels: enhancement

#77 BACKEND hosting image to backend
  .gitignore
  backend/admin_panel/migrations/0011_alter_event_image_alter_newsdetail_image_and_more.py
  backend/admin_panel/models.py
  backend/admin_panel/serializers.py
  backend/admin_panel/views.py
  backend/backend/settings.py
  backend/backend/urls.py
  backend/init/utils.py
Labels: enhancement

#82 fix(build): Fix build error, define const instead of let
  frontend/app/projects/page.tsx
  frontend/components/ProjectDetails.tsx
Labels: bug

#81 BACKEND sync worker in background
  backend/backend/health_check.py
  backend/backend/settings.py
  backend/init/apps.py
  backend/init/scheduler.py
  backend/init/utils.py
  backend/requirement.txt
Labels: enhancement

#87 Startup dashboard frontend linked with backend
  frontend/app/about/page.tsx
  frontend/app/components/projects/ProjectCard.tsx
  frontend/app/events/page.tsx
  frontend/app/globals.css
  frontend/app/news/page.tsx
  frontend/app/not-found.tsx
  frontend/app/page.tsx
  frontend/app/projects/page.tsx
  frontend/app/search/page.tsx
  frontend/app/signup/page.tsx
  frontend/app/startup/dashboard/page.tsx
  frontend/app/startup/messaging/page.tsx
  frontend/app/startup/opportunities/page.tsx
  frontend/app/startup/profile/page.tsx
  frontend/components/ChartBarLabel.tsx
  frontend/components/ChartRadialText.tsx
  frontend/components/Footer.tsx
  frontend/components/Navigation.tsx
  frontend/components/ProjectFilters.tsx
  frontend/components/ProjectOverview.tsx
  frontend/components/SignUpForm.tsx
  frontend/components/login-form.tsx
  frontend/components/ui/chart.tsx
  frontend/package.json
Labels: enhancement

#92 BACKEND - CRUD for projects, READ for events
  backend/exposed_api/event_serializers.py
  backend/exposed_api/event_views.py
  backend/exposed_api/project_views.py
  backend/exposed_api/urls.py
  backend/exposed_api/views.py
Labels: enhancement

#93 Add ci/cd
  .github/workflows/backend-ci.yml
  Makefile
  backend/admin_panel/tests.py
  backend/admin_panel/tests/test_models.py
  backend/exposed_api/tests.py
  backend/init/apps.py
  backend/init/scheduler.py
  pyproject.toml
Labels: enhancement

#94 Login and signup to backend
  backend/admin_panel/admin.py
  backend/admin_panel/migrations/0001_initial.py
  backend/admin_panel/migrations/0002_newsdetail_image.py
  backend/admin_panel/migrations/0003_event.py
  backend/admin_panel/migrations/0004_founder_startuplist_startupdetail.py
  backend/admin_panel/migrations/0005_alter_startupdetail_founders.py
  backend/admin_panel/migrations/0006_alter_founder_name.py
  backend/admin_panel/migrations/0007_user.py
  backend/admin_panel/migrations/0008_investor.py
  backend/admin_panel/migrations/0009_partner.py
  backend/admin_panel/migrations/0010_alter_startupdetail_founders.py
  backend/admin_panel/migrations/0011_alter_event_image_alter_newsdetail_image_and_more.py
  backend/admin_panel/models.py
  backend/admin_panel/serializers.py
  backend/admin_panel/views.py
  backend/authentication/migrations/0001_initial.py
  backend/authentication/migrations/0002_alter_customuser_role.py
  backend/entrypoint.sh
  backend/exposed_api/serializers.py
  backend/exposed_api/views.py
  backend/init/signals.py
  backend/init/utils.py
  frontend/app/projects/page.tsx
  frontend/app/startup/dashboard/page.tsx
  frontend/components/Navigation.tsx
  frontend/components/ProjectOverview.tsx
  frontend/components/SignUpForm.tsx
  frontend/components/login-form.tsx
  frontend/contexts/AuthContext.tsx
  frontend/lib/api.ts
Labels: enhancement

#98 BACKEND - GET user route and fixes
  backend/backend/urls.py
  backend/exposed_api/event_serializers.py
  backend/exposed_api/urls.py
  backend/exposed_api/user_views.py
  backend/exposed_api/views.py
  backend/init/utils.py
Labels: bug, enhancement

#100 BACKEND - auth check route
  backend/authentication/urls.py
  backend/authentication/views.py
Labels: enhancement

#101 BACKEND - crud news
  backend/exposed_api/news_views.py
  backend/exposed_api/urls.py
Labels: enhancement

#108 Create the skeleton of the admin area with blank pages
  frontend/app/admin/dashboard/page.tsx
  frontend/app/admin/events/page.tsx
  frontend/app/admin/news/page.tsx
  frontend/app/admin/projects/page.tsx
  frontend/app/admin/users/page.tsx
  frontend/components/AdminNavigation.tsx
  frontend/components/Navigation.tsx
Labels: enhancement

#107 Add ci/cd (frontend side)
  .github/workflows/backend-ci.yml
  .github/workflows/docker-build.yml
  .github/workflows/frontend-ci.yml
  frontend/.eslintrc.json
  frontend/app/api/socket/route.ts
  frontend/app/events/page.tsx
  frontend/app/globals.css
  frontend/app/not-found.tsx
  frontend/app/projects/page.tsx
  frontend/components/ProjectDetails.tsx
  frontend/components/ProjectFilters.tsx
  frontend/components/ProjectOverview.tsx
  frontend/components/ResetPasswordConfirmForm.tsx
  frontend/components/SignUpForm.tsx
  frontend/contexts/AuthContext.tsx
  frontend/eslint.config.mjs
  frontend/middleware.ts
  frontend/package.json
  frontend/websocket-proxy.js
  scripts/autolint_frontend.sh
Labels: enhancement

#114 BACKEND - CRUD for investors
  backend/exposed_api/investor_serializers.py
  backend/exposed_api/investor_views.py
  backend/exposed_api/urls.py
Labels: enhancement

#115 BACKEND - CRUD for partners
  backend/exposed_api/partner_serializers.py
  backend/exposed_api/partner_views.py
  backend/exposed_api/urls.py
Labels: enhancement

#117 Fix ci build docker
  backend/Dockerfile
  backend/backend/settings.py
Labels: enhancement

#123 Improve docker experience
  backend/.dockerignore
  backend/Dockerfile
  backend/health_check_script.py
  docker-compose.yml
  frontend/.dockerignore
Labels: enhancement

#125 feat(password-visibility): add toggle for password visibility in ResetPasswordConfirmForm
  frontend/components/ResetPasswordConfirmForm.tsx
Labels: enhancement

#129 BACKEND - unfound images are not an error
  backend/init/utils.py
  pyproject.toml
Labels: enhancement

#132 Created the public area News list with filters and details
  frontend/app/events/page.tsx
  frontend/app/globals.css
  frontend/app/news/page.tsx
  frontend/app/page.tsx
  frontend/components/NewsCard.tsx
  frontend/components/NewsFilters.tsx
  frontend/package.json
  frontend/types/news.ts
Labels: enhancement

#133 Admin Dashboard - Audit Log
  backend/auditlog/__init__.py
  backend/auditlog/admin.py
  backend/auditlog/apps.py
  backend/auditlog/migrations/0001_initial.py
  backend/auditlog/migrations/0002_alter_auditlog_type.py
  backend/auditlog/migrations/__init__.py
  backend/auditlog/models.py
  backend/auditlog/tests.py
  backend/auditlog/views.py
  backend/authentication/views.py
  backend/backend/settings.py
  backend/exposed_api/event_views.py
  backend/exposed_api/kpi_views.py
  backend/exposed_api/news_views.py
  backend/exposed_api/project_views.py
  backend/init/signals.py
  backend/models.py
  frontend/app/admin/dashboard/page.tsx
  frontend/services/DashboardService.ts
Labels: enhancement

#134 BACKEND - Fix auditlog error
  backend/authentication/views.py
  backend/exposed_api/event_views.py
  backend/exposed_api/news_views.py
  backend/exposed_api/project_views.py
Labels: bug

#137 Add users routes
  backend/exposed_api/founder_serializers.py
  backend/exposed_api/founder_views.py
  backend/exposed_api/urls.py
  backend/exposed_api/user_views.py
Labels: enhancement

#155 Add investor view
  frontend/app/admin/users/page.tsx
  frontend/app/investor/layout.tsx
  frontend/app/investor/messaging/page.tsx
  frontend/app/investor/opportunities/page.tsx
  frontend/components/AdminNewsForm.tsx
  frontend/components/AdminUser.tsx
  frontend/components/AdminUserForm.tsx
  frontend/components/InvestorNavigation.tsx
  frontend/components/Navigation.tsx
  frontend/components/ui/InputAvatar.tsx
  frontend/components/ui/comboBox.tsx
  frontend/middleware.ts
Labels: enhancement

#157 Implemented the advanced search functionnality in the frontend
  backend/exposed_api/search_views.py
  frontend/app/search/page.tsx
  frontend/types/search.ts
Labels: enhancement

#158 Fixed the favicon disappearing
  frontend/Dockerfile
Labels: enhancement

#159 Implement the new color palette and the new fonts wanted by JEB
  frontend/app/about/page.tsx
  frontend/app/admin/dashboard/page.tsx
  frontend/app/admin/events/page.tsx
  frontend/app/admin/news/page.tsx
  frontend/app/admin/projects/page.tsx
  frontend/app/admin/users/page.tsx
  frontend/app/events/page.tsx
  frontend/app/globals.css
  frontend/app/layout.tsx
  frontend/app/news/page.tsx
  frontend/app/not-found.tsx
  frontend/app/page.tsx
  frontend/app/projects/page.tsx
  frontend/app/search/page.tsx
  frontend/components/AdminEvent.tsx
  frontend/components/AdminEventForm.tsx
  frontend/components/AdminNavigation.tsx
  frontend/components/AdminNews.tsx
  frontend/components/AdminNewsForm.tsx
  frontend/components/AdminProjectForm.tsx
  frontend/components/AdminUser.tsx
  frontend/components/AdminUserForm.tsx
  frontend/components/Calendar.tsx
  frontend/components/ChartBarLabel.tsx
  frontend/components/ChartRadialText.tsx
  frontend/components/Navigation.tsx
  frontend/components/NewsCard.tsx
  frontend/components/NewsFilters.tsx
  frontend/components/ProjectDetails.tsx
  frontend/components/ProjectFilters.tsx
  frontend/components/ProjectOverview.tsx
  frontend/components/ProjectOverviewAdmin.tsx
  frontend/components/ResetPasswordConfirmForm.tsx
  frontend/components/ResetPasswordForm.tsx
  frontend/components/SignUpForm.tsx
  frontend/components/StartupNavigation.tsx
  frontend/components/login-form.tsx
Labels: enhancement

#160 FEATURE - opportunities matches (AI)
  backend/exposed_api/founder_views.py
  backend/exposed_api/opportunity_views.py
  backend/exposed_api/urls.py
  backend/requirement.txt
  frontend/app/startup/opportunities/page.tsx
  frontend/components/pdf/Startup.tsx
  pyproject.toml
Labels: enhancement

#166 Made color updates on the startup area
  frontend/app/startup/dashboard/page.tsx
  frontend/app/startup/opportunities/page.tsx
  frontend/app/startup/profile/page.tsx
  frontend/components/InvestorNavigation.tsx
  frontend/components/StartupNavigation.tsx
Labels: enhancement

#168 Add jeb logo
  frontend/components/AdminNavigation.tsx
  frontend/components/Navigation.tsx
  frontend/components/StartupNavigation.tsx
  frontend/components/svg/JEBLogo.tsx
Labels: enhancement

#169 Updated the investor nav to have the same style as the others
  frontend/components/InvestorNavigation.tsx
Labels: enhancement

#171 DARKMODE - Dark mode
  backend/authentication/templates/authentication/password_reset_email.html
  frontend/app/admin/dashboard/page.tsx
  frontend/app/admin/events/page.tsx
  frontend/app/admin/news/page.tsx
  frontend/app/admin/projects/page.tsx
  frontend/app/admin/users/page.tsx
  frontend/app/layout.tsx
  frontend/app/search/page.tsx
  frontend/app/startup/dashboard/page.tsx
  frontend/app/startup/opportunities/page.tsx
  frontend/app/startup/profile/page.tsx
  frontend/components/AdminEvent.tsx
  frontend/components/AdminEventForm.tsx
  frontend/components/AdminNavigation.tsx
  frontend/components/AdminNews.tsx
  frontend/components/AdminNewsForm.tsx
  frontend/components/AdminProjectForm.tsx
  frontend/components/AdminUser.tsx
  frontend/components/AdminUserForm.tsx
  frontend/components/ChatComponent.tsx
  frontend/components/InvestorNavigation.tsx
  frontend/components/Navigation.tsx
  frontend/components/NewThreadChat.tsx
  frontend/components/NewsCard.tsx
  frontend/components/ProjectDetails.tsx
  frontend/components/ProjectOverview.tsx
  frontend/components/ProjectOverviewAdmin.tsx
  frontend/components/StartupNavigation.tsx
  frontend/components/ui/dialog.tsx
  frontend/components/ui/theme-toggle.tsx
  frontend/contexts/ThemeContext.tsx
Labels: enhancement

#172 BACKEND - avg session duration
  backend/exposed_api/kpi_views.py
Labels: enhancement

#173 FRONTEND - theme button placement
  frontend/app/layout.tsx
  frontend/components/AdminNavigation.tsx
  frontend/components/InvestorNavigation.tsx
  frontend/components/Navigation.tsx
  frontend/components/StartupNavigation.tsx
  frontend/components/ui/theme-toggle.tsx
Labels: enhancement

#174 UNIT TESTS - some backend applications
  .github/workflows/backend-ci.yml
  backend/admin_panel/models.py
  backend/admin_panel/tests/__init__.py
  backend/admin_panel/tests/test_admin.py
  backend/admin_panel/tests/test_models.py
  backend/admin_panel/tests/test_serializers.py
  backend/admin_panel/tests/test_views.py
  backend/auditlog/tests.py
  backend/auditlog/tests/__init__.py
  backend/auditlog/tests/test_admin.py
  backend/auditlog/tests/test_apps.py
  backend/auditlog/tests/test_integration.py
  backend/auditlog/tests/test_models.py
  backend/authentication/tests/test_models.py
  backend/authentication/tests/test_serializers.py
  backend/authentication/tests/test_views.py
  backend/init/signals.py
  scripts/run_backend_tests.sh
Labels: enhancement
